#ifndef __LED__
#define __LED__

#define LED0_LED_RCC_ENABLE()  __HAL_RCC_GPIOA_CLK_ENABLE()
#define LED1_LED_RCC_ENABLE()  __HAL_RCC_GPIOA_CLK_ENABLE()

#define LED0_LED_GPIO  GPIOA
#define LED1_LED_GPIO  GPIOA

#define LED0_LED_PIN   GPIO_PIN_4
#define LED1_LED_PIN   GPIO_PIN_5

#define LED0(x)    x?HAL_GPIO_WritePin (LED0_LED_GPIO,LED0_LED_PIN,GPIO_PIN_SET):HAL_GPIO_WritePin (LED0_LED_GPIO,LED0_LED_PIN,GPIO_PIN_RESET)
#define LED1(x)      x?HAL_GPIO_WritePin (LED1_LED_GPIO,LED1_LED_PIN,GPIO_PIN_SET):HAL_GPIO_WritePin (LED1_LED_GPIO,LED1_LED_PIN,GPIO_PIN_RESET)

#define LED0_Toggle()  HAL_GPIO_TogglePin(LED0_LED_GPIO,LED0_LED_PIN)
#define LED1_Toggle()    HAL_GPIO_TogglePin(LED1_LED_GPIO,LED1_LED_PIN)

void LED_Init(void);
void LED_OS_TEST(void);
#endif
